version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    cooldown:
      default-days: 3
    groups:
      lint:
        dependency-type: "development"
        patterns:
          - "ruff*"
          - "mypy*"
          - "bandit*"
          - "semgrep*"
          - "codespell*"
          - "detect-secrets*"
          - "pre-commit*"
          - "types-*"
      docs:
        dependency-type: "development"
        patterns:
          - "mkdocs*"
          - "mike*"
          - "mdx-include*"
          - "typer*"
      dev:
        dependency-type: "development"
        patterns:
          - "pytest*"
          - "hypothesis*"
          - "ipython*"
          - "ipykernel*"
          - "nest-asyncio*"
      production:
        dependency-type: "production"
        patterns:
          - "*"
