# Preprocessed datasets for "Constrained Monotonic Neural Networks" (ICML 2023).
# Source: https://zenodo.org/records/7968969  DOI: 10.5281/zenodo.7968969
# License: CC-BY-4.0 (Runje & Shankaranarayana). NOT committed to git/LFS.
# Maintainer: fill in real SHA-256 sums after the first download.
[sha256]
