version: '3'
name: mononet-devcontainer-gpu-jax

services:
  python-3.13-mononet-gpu-jax:  # nosemgrep
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mononet-${USER}-python-3.13-gpu-jax
    volumes:
      - ../../:/workspaces/mononet:cached
    command: sleep infinity
    networks:
      - mononet-network-gpu-jax
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  mononet-network-gpu-jax:
    name: mononet-${USER}-network-gpu-jax
